#pragma config(Sensor, S1,     Stop,                sensorTouch)
#pragma config(Sensor, S2,     lightsensor,         sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     touchSensor,         sensorTouch)
#pragma config(Motor,  motorA,          l,             tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          r,             tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     lefts,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

bool CruiseControl = 0;

task main()
{
  eraseDisplay();
  while(true)
  {
    while(/*CruiseControl==false ||*/ SensorValue(Stop) != 1)
    {
    motor[l] = joystickCopy.joy1_y1; //Sets both motors to the left stick y axis.
    motor[r] = joystickCopy.joy1_y2; //sets both motors to the left stick x axis.
    nxtDisplayCenteredTextLine(3, "RMtrPwr: %d",motor[l]);
    nxtDisplayCenteredTextLine(4, "LMtrPwr: %d",motor[r]);
    }
    if(SensorValue(Stop) == 1)
    {
      bPlaySounds = true;
      nVolume = 5;
      /*
      PlaySoundFile("danger.rso");
      wait10Msec(50);
      PlaySoundFile("i.rso");
      wait10Msec(50);
      PlaySoundFile("cannot.rso");
      wait10Msec(50);
      PlaySoundFile("cannot.rso");
      wait10Msec(50);
      */
      PlaySoundFile("woop.rso");
      wait10Msec(50);
      PlaySoundFile("warning.rso");
      wait10Msec(50);
      PlaySoundFile("propulsion.rso");
      wait10Msec(50);
      PlaySoundFile("systems.rso");
      wait10Msec(50);
      PlaySoundFile("failure.rso");
      wait10Msec(50);
      PlaySoundFile("detected.rso");
      wait10Msec(50);
      /*
      PlaySoundFile("will.rso");
      wait10Msec(50);
      PlaySoundFile("attack.rso");
      PlaySoundFile("all.rso");
      wait10Msec(50);
      PlaySoundFile("human.rso");
      wait10Msec(50);
      PlaySoundFile("s.rso");
      wait10Msec(50);
      */
      SensorValue(Stop) = 0;
    }
    else
    {
      bPlaySounds = false;
      nVolume=0;
    }
    /*
    if(joy1Btn(00) == 1)                  // If Joy1-Button1 is pressed:
    {
        CruiseControl=true;            // TURN on Cruise Control
    }
    else                            // If Joy1-Button1 is NOT pressed:
    {
        CruiseControl=false;                 // Turn Motor A Off
    }
    */

  }

}
