#pragma config(Motor,  motorA,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "JoystickDriver.c"

task main()
{
  while(true)
  {
    getJoystickSettings(joystick);
  if (joy1Btn(1) == 1)
  {
 motor[left] = 100;
}
else
{
  motor[left] = 0;
}
}
}
