#pragma config(Sensor, S4,     IR,                  sensorI2CCustom)
#pragma config(Sensor, S2,     IR2,               sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S3,     Sonar,               sensorNone)
#pragma config(Motor,  motorA,          motorR,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorL,        tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/HTIRS2-driver.h"

int _dirDC = 0;
int _dirAC = 0;
int dcS1, dcS2, dcS3, dcS4, dcS5 = 0;
int acS1, acS2, acS3, acS4, acS5 = 0;

int dc[6];

task main()
{

//HTIRS2readAllDCStrength(S1,dcS1,dcS2,dcS3,dcS4,dcS5);

  while(true)
  {

  // Read the current non modulated signal direction
    _dirDC = HTIRS2readDCDir(IR);
    if (_dirDC < 0)
      break; // I2C read error occurred

    // read the current modulated signal direction
    _dirAC = HTIRS2readACDir(IR);
    if (_dirAC < 0)
      break; // I2C read error occurred

    // Read the individual signal strengths of the internal sensors
    // Do this for both unmodulated (DC) and modulated signals (AC)
    if (!HTIRS2readAllDCStrength(IR, dcS1, dcS2, dcS3, dcS4, dcS5))
      break; // I2C read error occurred
    if (!HTIRS2readAllACStrength(IR, acS1, acS2, acS3, acS4, acS5 ))
      break; // I2C read error occurred

      //int i;
      //for(i=0;i<5;i++);
     // {
       // switch(i);
        /*case 0: */
        dc[1] = dcS1;
        dc[2] = dcS2;
        dc[3] = dcS3;
        dc[4] = dcS4;
        dc[5] = dcS5;

        //int Sensor;
        int Dir;

         Dir = 0;
        case 1: Dir = dcS1;
        case 2: Dir = dcS2;
        case 3: Dir = dcS3;
        case 4: Dir = dcS4;
        case 5: Dir = dcS5;

        //Sensor = _dirDC;//SensorValue(IR);

      while( _dirDC < 5 && _dirDC > 0)
      {
        if(Dir>7)
        {
        motor[motorR] = 100-(Dir/255 * 100);
        }
        else
        {
          motor[motorR] = 0;
        }
      }

      while( _dirDC > 5)
      {
        if(Dir>7)
        {
        motor[motorL] = 100-(Dir/255 * 100);
        }
        else
        {
          motor[motorL] = 0;
        }
      }

      //if(!SensorValue(IR))

      while( _dirDC == 5)
      {
         if(Dir>7)
        {
        motor[motorL] = 100-(Dir/255 * 100);
        motor[motorR] = 100-(Dir/255 * 100);
        }
        else
        {
          motor[motorL] = 0;
          motor[motorR] = 0;
        }
        //if(SensorValue(Sonar) < 50)
        //{
        //  PlaySound(soundFastUpwardTones);
        //}
      }

      motor[motorR] = 0;
      motor[motorL] = 0;
  }
}
