#pragma config(Sensor, S2,     IR,                  sensorI2CCustom)
#pragma config(Sensor, S1,     Sonar,               sensorNone)
#pragma config(Motor,  motorB,          motorL,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorR,        tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/HTIRS2-driver.h"

int _dirDC = 0;
int _dirAC = 0;
int dcS1, dcS2, dcS3, dcS4, dcS5 = 0;
int acS1, acS2, acS3, acS4, acS5 = 0;

task main()
{

//HTIRS2readAllDCStrength(S1,dcS1,dcS2,dcS3,dcS4,dcS5);

  while(true)
  {
    // Read the current non modulated signal direction
    _dirDC = HTIRS2readDCDir(IR);
    if (_dirDC < 0)
      break; // I2C read error occurred

    // read the current modulated signal direction
    _dirAC = HTIRS2readACDir(IR);
    if (_dirAC < 0)
      break; // I2C read error occurred

    // Read the individual signal strengths of the internal sensors
    // Do this for both unmodulated (DC) and modulated signals (AC)
    if (!HTIRS2readAllDCStrength(IR, dcS1, dcS2, dcS3, dcS4, dcS5))
      break; // I2C read error occurred
    if (!HTIRS2readAllACStrength(IR, acS1, acS2, acS3, acS4, acS5 ))
      break; // I2C read error occurred


      if( _dirDC < 4 && _dirDC > 0)
      {
        motor[motorR] = -(((dcS1+dcS2)/2)/255)*100;
      }
      else if( _dirDC > 6)
      {
        motor[motorL] = -((dcS4)/255)*100;
      }
      //if(!_dirAC)
      else if( _dirDC < 6 && _dirDC > 4)
      {
        motor[motorR] = -(((dcS4+dcS5)/2)/255)*100;
        motor[motorL] = -(((dcS4+dcS5)/2)/255)*100;
        //if(SensorValue(Sonar) < 50)
        //{
        //  PlaySound(soundFastUpwardTones);
        //}
        //goto out;
      }
      //out:
      else
      {
      motor[motorR] = -0;
      motor[motorL] = -0;
      }
  }
}
