#pragma config(Sensor, S1,     HTSPB,                sensorI2CCustom9V)
	//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

	/*   HiTechnic Experimenter's Kit for the SuperPro

	This is a function that can be used to shift out (via spi) a byte to a device
	*/
void shiftOut(byte data);



#include "hitechnic-superpro.h"

	task main()
	{
		HTSPBsetupIO(HTSPB, 0x07);					//Sets digital pins 0,1,2	to outputs

	}
void shiftOut(byte data)
{
	data = data>>2;

}
