#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IRL,            sensorI2CCustom)
#pragma config(Sensor, S4,     IRR,            sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     backLeftMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     frontLeftMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     backRightMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     frontRightMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     M4Motor,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     LBoomMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     RBoomMotor,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    camServo1,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    camServo2,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Shoot when the IR beacon reaches a "sweet spot" in front of the IR beacons

#include "hitechnic-irseeker-v2.h"
#include "JoystickDriver.c"
#include "BotSystems.h"

//void holonomicBeepAtIR();
//void trackIR();
//void stopAllMotors();
void updateSensors();
void shootAtIR();
int getAvgDir();
int getAvgStr(int acXr, int acXl);

int _dirACL;
int _dirACR;
int acS1L, acS2L, acS3L, acS4L, acS5L;
int acS1R, acS2R, acS3R, acS4R, acS5R;
int avgDir, avgStr;

tHTIRS2DSPMode _mode = DSP_1200;

task main()
{
	getJoystickSettings(joystick);
	eraseDisplay();
	while(true)
	{
		updateSensors();
		avgDir = getAvgDir();
		avgStr = getAvgStr(acS3R, acS3L);
		nxtDisplayCenteredTextLine(3, "%d", "%d", avgDir, avgStr);
	}

	//holonomicStopAtIR();
	//shootAtIR();
}

void shootAtIR()  //good zone: both dirs 5, both strengths in 3 from 60-90
{
	//-----------------------------Setup-------------------------------------------------
	updateSensors();
	initSystems();

	//-----------------------------Moving the Bot--------------------------------------------
	motor[frontLeftMotor] = 50;
	motor[frontRightMotor] = 50;
	motor[backLeftMotor] = -50;
	motor[backRightMotor] = -50;
	if(getAvgDir() == 5 && getAvgStr(acS3R, acS3L) > 40)  //change to zone 4?
	{
		pullBack(1500,100);  //load...
		fire();              //fire
	}
}

int getAvgDir()
{
	return (_dirACL + _dirACR) / 2;
}

int getAvgStr(int acXr, int acXl)
{
	return (acXr + acXl) / 2;
}

void updateSensors()
{
	HTIRS2setDSPMode(IRL, _mode);
	HTIRS2setDSPMode(IRR, _mode);

	_dirACL = HTIRS2readACDir(IRL);
	_dirACR = HTIRS2readACDir(IRR);

	HTIRS2readAllACStrength(IRL,  acS1L,  acS2L,  acS3L,  acS4L,  acS5L);
	HTIRS2readAllACStrength(IRR,  acS1R,  acS2R,  acS3R,  acS4R,  acS5R);
}

/*void trackIR()
{
//-----------------------------IR Setup-------------------------------------------------
HTIRS2setDSPMode(IRL, _mode);
HTIRS2setDSPMode(IRR, _mode);

_dirACL = HTIRS2readACDir(IRL);
_dirACR = HTIRS2readACDir(IRR);

HTIRS2readAllACStrength(IRL,  acS1L,  acS2L,  acS3L,  acS4L,  acS5L);
HTIRS2readAllACStrength(IRR,  acS1R,  acS2R,  acS3R,  acS4R,  acS5R);

int temp = 0;

for(int i = 0; i < 10; i++)
{
temp += _dirACL + _dirACR;
}

avgDir = temp / 20;

//-----------------------------Moving the Bot--------------------------------------------
if(avgDir < 5)
{
if(avgDir < 4)
{
motor[frontLeft] = -50;
motor[frontRight] = 50;
motor[backLeft] = 50;
motor[backRight] = -50;
}
else  //avgDir == 4
{
motor[frontLeft] = 0;
motor[frontRight] = 50;
motor[backLeft] = -50;
motor[backRight] = 0;
}
}
else if(avgDir > 5)
{
if(avgDir > 6)
{
motor[frontLeft] = 50;
motor[frontRight] = -50;
motor[backLeft] = -50;
motor[backRight] = 50;
}
else  //avgDir == 6
{
motor[frontLeft] = 50;
motor[frontRight] = 0;
motor[backLeft] = 0;
motor[backRight] = -50;
}
}
else  //avgDir == 5
{
motor[frontLeft] = 50;
motor[frontRight] = 50;
motor[backLeft] = -50;
motor[backRight] = -50;
}
}*/

/*void stopAllMotors()
{
motor[frontLeft] = 0;
motor[frontRight] = 0;
motor[backLeft] = 0;
motor[backRight] = 0;
}*/
