#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
void controlledDriveTank()
{
	float speed;
	float factor;
	int servo1pos;
	while(true)
	{
		getJoystickSettings(joystick);  // Update Buttons and Joysticks
		if( joy1Btn(3) )//This provides a speed toggle,
		{
			speed = !speed;
			wait1Msec(10);
		}
		if(speed)
		{
			factor = 1.81429;
		}
		else
		{
			factor = 5.00; //Slows the driving down to a reasonable amount.
		}
		motor[rightMotor] = joystick.joy1_y1/factor;
		motor[leftMotor] = joystick.joy1_y2/factor;
		if((joy1Btn(1))) servo1pos += 2;
		else if((joy1Btn(2))) servo1pos -= 2;
		servo[servo1] = servo1pos;
		wait1Msec(20);

		//	 if((joy1Btn(10)))
		//	   break;
	}
}
task main()
{
	//servo[servo1]=0;
	controlledDriveTank();
}
