#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
void controlledDriveEasy()
{
	float speed;
	float factor;
	int driveData;

	while(true)
	{
		getJoystickSettings(joystick);  // Update Buttons and Joysticks
		if(joy1Btn(3))//This provides a speed toggle,
		{
			speed = !speed;
			wait1Msec(10);
		}
		if(speed)
		{
			factor = 1.81429;
		}
		else
		{
			factor = 5.00; //Slows the driving down to a reasonable amount.
		}

		driveData = joystick.joy1_y1 / factor;

		motor[leftMotor] = joystick.joy1_x2 / factor - driveData;

		motor[rightMotor] =  joystick.joy1_x2 / factor + driveData;


		//if(joystick.joy1_x2 < 0)
		//{
		//	motor[leftMotor] = joystick.joy1_x2 / factor;
		//}
		//else if(joystick.joy1_x2 >= 0)
		//{
		//	motor[rightMotor] = joystick.joy1_x2 / factor;
		//}


		//motor[leftMotor] = joystick.joy1_y1/-factor;
		//motor[rightMotor] = joystick.joy1_y2/factor;

		if((joy1Btn(10)))
			break;
	}
}
task main()
{
	controlledDriveEasy();
}
