#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_2,     frontLeftMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     frontRightMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     backLeftMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     backRightMotor, tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
0
------------0
|					 |0
|					 |
0	|					 |
------------
0
*/

//Left Joystick is joystick 1 (Y1,X1), and right joystick is joystick2 (Y2, X2)

int Y1, Y2, X1, X2;

void omniDrive();
#include "JoystickDriver.c"
task main()
{
	//eraseDisplay();
	//	nxtDisplayCenteredBigTextLine(4,"X %3d",avgX);
	while(true)
	{
		omniDrive();
	}

}
void omniDrive()
{

	getJoystickSettings(joystick);

	Y1 = joystick.joy1_y1 / -1.28;
	Y2 = joystick.joy1_y2 / -1.28;
	X1 = joystick.joy1_x1 / 1.28;
	X2 = joystick.joy1_x2 / 1.28;

	motor[frontRightMotor] = -Y2 - X2 - X1;
	motor[backRightMotor] =  Y2 - X2 + X1;
	motor[frontLeftMotor] = -Y2 + X2 + X1;
	motor[backLeftMotor] =  Y2 + X2 - X1;

	wait1Msec(100);
}
