#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftFront,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftBack,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightFront,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rightBack,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     armLeft,       tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     armRight,      tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

bool isnotStartup = false;
int button;


task main()
{
  while(isnotStartup == false)
  {
   nVolume=10;
   //PlaySound(soundFastUpwardTones);
   //PlaySound(soundDownwardTones);
  //PlaySoundFile("everything'sonline.rso");
  //wait10Msec(30);
  PlaySoundFile("on.rso");
  PlaySoundFile("line.rso");
  isnotStartup = true;
  }
  getJoystickSettings(joystick);
  //getPCJoystickSettings(joystick);
  while(true)
  {
    button = joy1Btn(01);
    motor[leftFront] = joystickCopy.joy1_y1;
    motor[leftBack] = joystickCopy.joy1_y1;
    motor[rightFront] = joystickCopy.joy1_y2;
    motor[rightBack] = joystickCopy.joy1_y2;
    motor[armLeft]= joystickCopy.joy2_x1/2;
    motor[armRight]=joystickCopy.joy2_x2/2;


    if(joy1Btn(6))//Left up
    {
      PlaySound(soundException);
      //motor[armLeft]=50;
    }
    else if(joy1Btn(8) != -1)//Left down
    {
      //motor[armLeft]=-50;
    }
    else
    {
      //motor[armLeft]=0;
    }
    if(joy1Btn(5)==1 != -1)//Right up
    {
      //motor[armRight]=50;
    }
    else if(joy1Btn(7) != -1)//Right down
    {
      //motor[armRight]=-50;
    }
    else
    {
      //motor[armRight]=0;

    }
  }
}
