#pragma config(Sensor, S1,     Stop,                sensorTouch)
#pragma config(Sensor, S2,     lightsensor,         sensorLightActive)
#pragma config(Sensor, S3,     SONAR,               sensorSONAR)
#pragma config(Motor,  motorB,          l,             tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          r,             tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     touchSensor,         sensorTouch)
#pragma config(Motor,  motorA,          l,             tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          r,             tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     lefts,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

bool CruiseControl = false;
float WallRightDist;
float WallLeftDist;
float WallFrontDist;
bool isWall = false;
float larr;

task main()
{
  while(true)
  {
    nVolume=4;
    while(SensorValue(SONAR) < 20)
    {
          larr = SensorValue(SONAR);
      //PlayImmediateTone(SensorValue(SONAR)+250, 1);
      PlaySoundFile("obstacle.rso");
//      wait10Msec(25);
      PlaySoundFile("is.rso");
//      wait10Msec(25);
      string distance = "";
      //SensorValue(SONAR).".rso";
      StringFormat(distance,"%i.rso",larr);
      PlaySoundFile(distance);
//      wait10Msec(50);
      PlaySoundFile("centimeters.rso");
//      wait10Msec(50);
      PlaySoundFile("away.rso");
    }
    wait10Msec(1);
  }
}
