#pragma config(Sensor, S1,     IR,                  sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S2,     IR2,               sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S3,     Sonar,               sensorNone)
#pragma config(Motor,  motorB,          motorL,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorR,        tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/HTIRS2-driver.h"

int _dirDC = 0;
int _dirAC = 0;
int dcS1, dcS2, dcS3, dcS4, dcS5 = 0;
//int acS1, acS2, acS3, acS4, acS5 = 0;

task main()
{

//HTIRS2readAllDCStrength(S1,dcS1,dcS2,dcS3,dcS4,dcS5);

  while(true)
  {
      while( SensorValue(IR) < 5 && SensorValue(IR) > 0)
      {
        motor[motorR] = 2555;
      }
      while( SensorValue(IR) > 5)
      {
        motor[motorL] = 2555;
      }
      //if(!SensorValue(IR))
      while( SensorValue(IR) == 5)
      {
        motor[motorR] = 2555;
        motor[motorL] = 2555;
        //if(SensorValue(Sonar) < 50)
        //{
        //  PlaySound(soundFastUpwardTones);
        //}
      }

      while( SensorValue(IR2) < 5 && SensorValue(IR2) > 0)
      {
        motor[motorL] = -2555;
      }
      while( SensorValue(IR2) > 5)
      {
        motor[motorR] = -2555;
      }
      //if(!SensorValue(IR))
      while( SensorValue(IR2) == 5)
      {
        motor[motorR] = -2555;
        motor[motorL] = -2555;
        //if(SensorValue(Sonar) < 50)
        //{
        //  PlaySound(soundFastUpwardTones);
        //}
      }
      motor[motorR] = 0;
      motor[motorL] = 0;
  }
}
