#pragma config(Sensor, S1,     sound1,          sensorSoundDBA)
#pragma config(Sensor, S4,     sound2,           sensorSoundDBA)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int snd1, snd2;
string dir;

int GetDir(int snd1, int snd2)
{
  //string dir;

  if(abs(snd1-snd2)>10)
  {
	  if(snd1>snd2)
	  {
	    dir = "left";
	  }
	  else
	  {
	    dir = "right";
	  }
	}
	else
	{
	  dir = "center";
	}/*
	if(snd1>20 && snd2>20)
	{
	  dir = "everywhere";
	}*/
	return 1/*r*/;
}

task main()
{
  nVolume = 10;
  while(true && nNxtButtonPressed != kButtonCenter)
  {

    snd1 = SensorValue(sound1);
    snd2 = SensorValue(sound2);
    nxtDisplayTextLine(0,"SND1: %d  SND2: %d",snd1,snd2);
    nxtDisplayTextLine(2,"Diff: %d",abs(snd1-snd2));
    GetDir(snd1,snd2);
    nxtDisplayTextLine(4,"Sound is to the");
    nxtDisplayTextLine(5,"%s.",dir);
    /*if(dir=="everywhere")
    {
      PlaySoundFile("everywhere.rso");
	    wait10Msec(50);
	    ClearSounds();
	  }*/
    if(dir=="left")
	  {
	    PlaySoundFile("left.rso");
	    //PlaySound(soundShortBlip);
	    wait10Msec(50);
	    ClearSounds();
	  }
	  if(dir=="right")
	  {
	    //PlaySound(soundBlip);
	    PlaySoundFile("right.rso");
	    wait10Msec(50);
	    ClearSounds();
	  }
  }
}
