#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRL,            sensorI2CCustom)
#pragma config(Sensor, S3,     IRR,            sensorI2CCustom)
#pragma config(Motor,  motorA,          magLeft,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          magRight,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     backRightMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     frontRightMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     M4Motor,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     LBoomMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     RBoomMotor,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     backLeftMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     frontLeftMotor, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    camServo1,            tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    camServo2,            tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "joystickdriver.c"

#define STOP 0
#define IN 1
#define OUT -1

byte mag = STOP;

//float factor = .63;
//float factor = .1969;
float factor = 1.27;

int e;

task OpenGate();


task main()
{
	nVolume = 2;
	nMotorEncoder[magLeft] = 0;
	while(true)
	{
		getJoystickSettings(joystick);
		if(nMotorEncoder[magLeft] > 180 || nMotorEncoder[magLeft] < -180) nMotorEncoder[magLeft] = 0;
		if(nMotorEncoder[magRight] > 180 || nMotorEncoder[magRight] < -180) nMotorEncoder[magRight] = 0;
		//e = nMotorEncoder[magLeft];
		//e = nMotorEncoder[magLeft];
		nxtDisplayCenteredBigTextLine(4, "%d", nMotorEncoder[magLeft]);
		if(/*joystick.joy1_y1 > 1*/ nNxtButtonPressed == 3)
			StartTask(OpenGate, 7);
		//while(joy1Btn(1))
		//{
		//	motor[magLeft] = joystick.joy1_y1 / 1.27;
		//	nxtDisplayCenteredBigTextLine(4, "%d", nMotorEncoder[magLeft]);
		//	if(nMotorEncoder[magLeft] > 180 || nMotorEncoder[magLeft] < -180) nMotorEncoder[magLeft] = 0;
		//	if(nMotorEncoder[magRight] > 180 || nMotorEncoder[magRight] < -180) nMotorEncoder[magRight] = 0;
		//}
		if(joy1Btn(6) || joy2Btn(6))
			mag = IN;
		if(joy1Btn(5) || joy2Btn(5))
			mag = OUT;
		if(joy1Btn(5) && joy1Btn(6) || joy2Btn(5) && joy2Btn(6))
			mag = STOP;

		if(mag == IN)
		{
			motor[magLeft] = 100;
			motor[magRight] = 100;
		}
		else if(mag == OUT)
		{
			motor[magLeft] = -100;
			motor[magRight] = -100;
		}
		else
		{
			motor[magLeft] = 0;
			motor[magRight] = 0;
		}

		if(joy1Btn(3))
		{
			StopTask(OpenGate);
			PlaySound(soundBlip);
		}
	}
}

task OpenGate()
{
	eraseDisplay();
	//nMotorEncoder[magLeft] = e;
	getJoystickSettings(joystick);
	while(true)
	{
		if(nMotorEncoder[magLeft] > 180 || nMotorEncoder[magLeft] < -180) nMotorEncoder[magLeft] = 0;
		if(nMotorEncoder[magRight] > 180 || nMotorEncoder[magRight] < -180) nMotorEncoder[magRight] = 0;

		bFloatDuringInactiveMotorPWM = false;
		nxtDisplayCenteredBigTextLine(4, "%d", nMotorEncoder[magLeft]);

		//if(/*joystick.joy1_y1 > 1*/ nNxtButtonPressed == 3)
		//{
		if(nMotorEncoder[magLeft] > 5)
		{
			motor[magLeft] = -100;
		}
		else if(nMotorEncoder[magLeft] < -5)
		{
			motor[magLeft] = 100;
		}
		else
		{
			motor[magLeft] = 0;
		}

		if(nMotorEncoder[magRight] > 5)
		{
			motor[magRight] = -100;
		}
		else if(nMotorEncoder[magLeft] < -5)
		{
			motor[magRight] = 100;
		}
		else
		{
			motor[magRight] = 0;
		}
	}
}
