#pragma config(Sensor, S1,     HTSPB,          sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define TEST_PIN 0x01		//Clock high then low when data is set

#include "hitechnic-superpro.h"
//Hello


task main()
{
	HTSPBsetupIO(HTSPB,TEST_PIN);
	while(true)
	{
	  HTSPBwriteIO(HTSPB, 0x00);	//Pin low
	  HTSPBwriteIO(HTSPB, TEST_PIN);			//Pin high
	}
}
