#pragma config(Sensor, S1,     HTSPB,          sensorI2CCustom9V)
#pragma config(Sensor, S2,     EOPD,           sensorAnalogInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-eopd.h"
/*   HiTechnic Experimenter's Kit for the SuperPro

This is a function that can be used to shift out (via spi) a byte to a device
*/
#define CSA_PIN 0x04		//Pull down when sending data to device
#define SDI_PIN 0x02		//Set to digital value you want to send
#define SCK_PIN 0x01		//Clock high then low when data is set
int sevenSeg[] =
{0x3F,0x06, 0x5B, 0x4F, 0x66, 0x6D, 0x7D, 0x07, 0x7F, 0x6F, 0x5F, 0x7C, 0x58, 0x5E, 0x7B, 0x71 };
/*
000
|||-Clock pin
||
||--Data pin
|
|---Chip select pin
Manually need to set CSA pin outside of function EXAMPLE
HTSPBwriteIO(HTSPB, 0x00);
shiftOut(0x45);
shiftOut(0x6A);
HTSPBwriteIO(HTSPB, CSA_PIN);						//Set chip select pin high when not sending data!!
*/
byte LSD;
byte MSD;
int raw;
/*
task main()
{

while(true)
	{
  	eraseDisplay();
  	raw = HTEOPDreadRaw(EOPD);
	  nxtDisplayBigTextLine(4,"x %3d",raw);
	  wait10Msec(10);
}

}

*/

void shiftOut(byte data);



#include "hitechnic-superpro.h"

task main()
{
	HTSPBsetupIO(HTSPB,CSA_PIN | SDI_PIN | SCK_PIN);
	while(true)
	{
	  raw = HTEOPDreadRaw(EOPD);					//Read raw value from EOPD
	  HTSPBwriteIO(HTSPB, 0x00);					//CSA low
	  LSD = raw & 0x0F;											//Get last nibble of number
	  MSD = (raw & 0xF0) >> 4;						//Get first nibble and put in last nibble place
	  shiftOut(sevenSeg[LSD]);						//Shift out the least significant digit
		shiftOut(sevenSeg[MSD]);						//Shift out the most significant digit
		HTSPBwriteIO(HTSPB, CSA_PIN);					//Set chip select pin high when not sending data!!
		wait1Msec(1);
	}
}
void shiftOut(byte data)								//Function shifts out 1 byte
{
	int i;
	for(i = 0; i < 8; i++)
	{
		if(data & 0x80)							//If MSB masked with 0x80 == 1 then data = 1
		{
			HTSPBwriteIO(HTSPB, SDI_PIN);			//Data high
			wait1Msec(1);
			HTSPBwriteIO(HTSPB, SDI_PIN | SCK_PIN);	//Clock high
		}
		else																//If MSB masked with 0x80 == 0 then data = 0
		{
			HTSPBwriteIO(HTSPB, 0x00);				//Data low
			wait1Msec(1);
			HTSPBwriteIO(HTSPB, SCK_PIN);			//Clock high
		}
		wait1Msec(1);
		HTSPBwriteIO(HTSPB, 0x00);					//Clock low
		data = data<<1;										//Shift over to get next MSB bit
	}
}
