#pragma config(Sensor, S1,     HTSPB,                sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
HiTechnic Experimenter's Kit for the SuperPro
*/

#define SDA_PIN 0x02		//Set to digital value you want to send
#define SCK_PIN 0x01		//Clock high then low when data is set

/*
00
||-Clock pin
|
|--Data pin

*/
void I2COut(byte data);

#include "hitechnic-superpro.h"

task main()
{
	HTSPBsetupIO(HTSPB,SDA_PIN | SCK_PIN);			//Set bot SDA and SCK high for initial i2c
	I2COut(0x54);
}

void I2COut(byte data)								//Function shifts out 1 byte
{
	HTSPBwriteIO(HTSPB, SCK_PIN);				//Clock high -> data low BEGIN!!!
	int i;
	for(i = 0; i < 8; i++)
	{
		if(data & 0x80)							//If MSB masked with 0x80 == 1 then data = 1
		{
			HTSPBwriteIO(HTSPB, SDA_PIN);			//Data high
			wait1Msec(1);
			HTSPBwriteIO(HTSPB, SDA_PIN | SCK_PIN);	//Clock high
		}
		else																//If MSB masked with 0x80 == 0 then data = 0
		{
			HTSPBwriteIO(HTSPB, 0x00);				//Data low
			wait1Msec(1);
			HTSPBwriteIO(HTSPB, SCK_PIN);			//Clock high
		}
		wait1Msec(1);
		HTSPBwriteIO(HTSPB, 0x00);					//Clock low
		data = data<<1;										//Shift over to get next MSB bit
	}
	HTSPBwriteIO(HTSPB, SCK_PIN);					//Clock high -> data low END!!!
	wait1Msec(1);
	HTSPBwriteIO(HTSPB, SCK_PIN | SCK_PIN);

}
