#pragma config(Sensor, S1,     HTSPB,                sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*   HiTechnic Experimenter's Kit for the SuperPro

This is a function that can be used to shift out (via spi) a byte to a device
*/
void shiftOut(byte data);



#include "hitechnic-superpro.h"

task main()
{
	/*
	000
	|||-Clock pin
	||
	||--Data pin
	|
	|---Chip select pin
	*/
	HTSPBsetupIO(HTSPB, 0x07);					//Sets digital pins 0,1,2	to outputs
	HTSPBwriteIO(HTSPB, 0x04);					//Sets pin 3 high -- chip select pin	== 0000 0100
}
void shiftOut(byte data)							//Function shifts out 1 byte
{
	int i;
	HTSPBwriteIO(HTSPB, 0x01);						//Sets pin 3 low-- chip selected start data shifting, set clock high == 0000 0001
	for(i = 0; i < 8; i++)
	{
		if((data & 0x80) == 1)							//If MSB masked with 0x80 == 1 then data = 1, clock = 0
		{
			HTSPBwriteIO(HTSPB, 0x03);				//Sets data high == 0000 0011
			wait1Msec(1);
			HTSPBwriteIO(HTSPB, 0x02);				//Sets data high clock low == 0000 0010
		}
		else
		{
			HTSPBwriteIO(HTSPB, 0x01);				//Sets data low
			wait1Msec(1);
			HTSPBwriteIO(HTSPB, 0x00);				//Clock low
		}
		HTSPBwriteIO(HTSPB, 0x01);					//Clock high
		data = data <<2;
	}
	HTSPBwriteIO(HTSPB, 0x04);						//Chip select high end of data transfer
}
