#pragm
a config(Sensor, S1,     Stop,                sensorTouch
#pragma config(Sensor, S2,     lightsensor,         sensorLightActive)
#pragma config(Sensor, S3,     SONAR,               sensorSONAR)
#pragma config(Motor,  motorB,          l,             tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          r,             tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     touchSensor,         sensorTouch)
#pragma config(Motor,  motorA,          l,             tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          r,             tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     lefts,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

bool CruiseControl = false;

task main()
{
  eraseDisplay();
  while(true)
  {
    while(CruiseControl==false && SensorValue(Stop) != 1)
    {
    motor[l] = joystickCopy.joy1_y1; //Sets both motors to the left stick y axis.
    motor[r] = joystickCopy.joy1_y2; //sets both motors to the left stick x axis.
    nxtDisplayCenteredTextLine(3, "RMtrPwr: %d",motor[l]);
    nxtDisplayCenteredTextLine(4, "LMtrPwr: %d",motor[r]);
    }
    while(SensorValue(SONAR) < 50)
    {
      PlayImmediateTone(SensorValue(SONAR), 1);
      /*
      PlaySoundFile("obstacle.rso");
      wait10Msec(50);
      PlaySoundFile("is.rso");
      wait10Msec(50);
      //string distance[5]
      //format(distance,5,"%i.rso",SensorValue(SONAR));
      //PlaySoundFile(distance);
      wait10Msec(50);
      PlaySoundFile("centimeters.rso");
      wait10Msec(50);
      PlaySoundFile("away.rso");
      /*
    }
    if(SensorValue(Stop) == 1)
    {
      bPlaySounds = true;
      nVolume = 15;
      /*
      PlaySoundFile("alert.rso");
      wait10Msec(50);
      PlaySoundFile("diagnostic.rso");
      wait10Msec(50);
      PlaySoundFile("systems.rso");
      wait10Msec(50);
      PlaySoundFile("indicate.rso");
      wait10Msec(50);
      PlaySoundFile("failure.rso");
      wait10Msec(50);
      SensorValue(Stop) = 0;
    }
    else
    {
      bPlaySounds = false;
      nVolume=0;
    }
    while(joy1Btn(1))
    {
      if(CruiseControl==true)
      {
        CruiseControl=false;
      }
      else
      {
        CruiseControl=true;
      }
    }
  }

}
